--- !ruby/object:Gem::Specification 
name: rio
version: !ruby/object:Gem::Version 
  version: 0.4.3
platform: ruby
authors: 
- Christopher Kleckner
autorequire: rio
bindir: bin
cert_chain: []

date: 2009-05-21 00:00:00 -07:00
default_executable: 
dependencies: []

description: 
email: rio4ruby@rubyforge.org
executables: []

extensions: []

extra_rdoc_files: []

files: 
- lib/rio.rb
- lib/rio/abstract_method.rb
- lib/rio/argv.rb
- lib/rio/arycopy.rb
- lib/rio/assert.rb
- lib/rio/base.rb
- lib/rio/callstr.rb
- lib/rio/const.rb
- lib/rio/construct.rb
- lib/rio/constructor.rb
- lib/rio/context.rb
- lib/rio/context/autoclose.rb
- lib/rio/context/copying.rb
- lib/rio/context/cxx.rb
- lib/rio/context/dir.rb
- lib/rio/context/gzip.rb
- lib/rio/context/methods.rb
- lib/rio/context/skip.rb
- lib/rio/context/stream.rb
- lib/rio/cp.rb
- lib/rio/def.rb
- lib/rio/dir.rb
- lib/rio/doc.rb
- lib/rio/doc/EXAMPLES.rb
- lib/rio/doc/HOWTO.rb
- lib/rio/doc/INDEX.rb
- lib/rio/doc/INTRO.rb
- lib/rio/doc/OPTIONAL.rb
- lib/rio/doc/SYNOPSIS.rb
- lib/rio/entrysel.rb
- lib/rio/exception.rb
- lib/rio/exception/copy.rb
- lib/rio/exception/notimplemented.rb
- lib/rio/exception/notsupported.rb
- lib/rio/exception/open.rb
- lib/rio/exception/state.rb
- lib/rio/ext.rb
- lib/rio/ext/csv.rb
- lib/rio/ext/if.rb
- lib/rio/ext/mp3info.rb
- lib/rio/ext/splitlines.rb
- lib/rio/ext/yaml.rb
- lib/rio/ext/yaml/doc.rb
- lib/rio/ext/yaml/tie.rb
- lib/rio/ext/zipfile.rb
- lib/rio/ext/zipfile/fs.rb
- lib/rio/ext/zipfile/rl.rb
- lib/rio/ext/zipfile/rootdir.rb
- lib/rio/ext/zipfile/state.rb
- lib/rio/ext/zipfile/wrap.rb
- lib/rio/factory.rb
- lib/rio/file.rb
- lib/rio/filter.rb
- lib/rio/filter/closeoneof.rb
- lib/rio/filter/gzip.rb
- lib/rio/fs/base.rb
- lib/rio/fs/impl.rb
- lib/rio/fs/native.rb
- lib/rio/fs/stream.rb
- lib/rio/fs/url.rb
- lib/rio/ftp/conncache.rb
- lib/rio/ftp/dir.rb
- lib/rio/ftp/fs.rb
- lib/rio/ftp/ftpfile.rb
- lib/rio/grande.rb
- lib/rio/handle.rb
- lib/rio/if.rb
- lib/rio/if/basic.rb
- lib/rio/if/csv.rb
- lib/rio/if/dir.rb
- lib/rio/if/file.rb
- lib/rio/if/fileordir.rb
- lib/rio/if/grande.rb
- lib/rio/if/grande_entry.rb
- lib/rio/if/grande_stream.rb
- lib/rio/if/internal.rb
- lib/rio/if/path.rb
- lib/rio/if/rubyio.rb
- lib/rio/if/string.rb
- lib/rio/if/temp.rb
- lib/rio/if/test.rb
- lib/rio/if/yaml.rb
- lib/rio/ioh.rb
- lib/rio/iomode.rb
- lib/rio/ios/fail.rb
- lib/rio/ios/generic.rb
- lib/rio/ios/mode.rb
- lib/rio/ios/null.rb
- lib/rio/iowrap.rb
- lib/rio/kernel.rb
- lib/rio/local.rb
- lib/rio/match.rb
- lib/rio/matchrecord.rb
- lib/rio/no_warn.rb
- lib/rio/nullio.rb
- lib/rio/open3.rb
- lib/rio/ops/construct.rb
- lib/rio/ops/create.rb
- lib/rio/ops/dir.rb
- lib/rio/ops/either.rb
- lib/rio/ops/file.rb
- lib/rio/ops/path.rb
- lib/rio/ops/stream.rb
- lib/rio/ops/stream/input.rb
- lib/rio/ops/stream/output.rb
- lib/rio/ops/stream/read.rb
- lib/rio/ops/stream/write.rb
- lib/rio/ops/symlink.rb
- lib/rio/path.rb
- lib/rio/path/reset.rb
- lib/rio/piper.rb
- lib/rio/piper/cp.rb
- lib/rio/prompt.rb
- lib/rio/rectype.rb
- lib/rio/rl/base.rb
- lib/rio/rl/builder.rb
- lib/rio/rl/chmap.rb
- lib/rio/rl/fs2url.rb
- lib/rio/rl/ioi.rb
- lib/rio/rl/path.rb
- lib/rio/rl/pathmethods.rb
- lib/rio/rl/uri.rb
- lib/rio/rl/withpath.rb
- lib/rio/scheme/aryio.rb
- lib/rio/scheme/cmdio.rb
- lib/rio/scheme/cmdpipe.rb
- lib/rio/scheme/fd.rb
- lib/rio/scheme/ftp.rb
- lib/rio/scheme/http.rb
- lib/rio/scheme/null.rb
- lib/rio/scheme/path.rb
- lib/rio/scheme/stderr.rb
- lib/rio/scheme/stdio.rb
- lib/rio/scheme/strio.rb
- lib/rio/scheme/sysio.rb
- lib/rio/scheme/tcp.rb
- lib/rio/scheme/temp.rb
- lib/rio/state.rb
- lib/rio/state/error.rb
- lib/rio/stream.rb
- lib/rio/stream/base.rb
- lib/rio/stream/duplex.rb
- lib/rio/stream/open.rb
- lib/rio/symantics.rb
- lib/rio/tempdir.rb
- lib/rio/to_rio.rb
- lib/rio/to_rio/all.rb
- lib/rio/to_rio/array.rb
- lib/rio/to_rio/io.rb
- lib/rio/to_rio/object.rb
- lib/rio/to_rio/string.rb
- lib/rio/uri/file.rb
- lib/rio/util.rb
- lib/rio/version.rb
- README
- lib/rio.rb
- lib/rio/doc/EXAMPLES.rb
- lib/rio/doc/HOWTO.rb
- lib/rio/doc/INDEX.rb
- lib/rio/doc/INTRO.rb
- lib/rio/doc/OPTIONAL.rb
- lib/rio/doc/SYNOPSIS.rb
- lib/rio/if/basic.rb
- lib/rio/if/csv.rb
- lib/rio/if/dir.rb
- lib/rio/if/file.rb
- lib/rio/if/fileordir.rb
- lib/rio/if/grande.rb
- lib/rio/if/grande_entry.rb
- lib/rio/if/grande_stream.rb
- lib/rio/if/internal.rb
- lib/rio/if/path.rb
- lib/rio/if/rubyio.rb
- lib/rio/if/string.rb
- lib/rio/if/temp.rb
- lib/rio/if/test.rb
- lib/rio/if/yaml.rb
- lib/rio/constructor.rb
- lib/rio/kernel.rb
- ex/catcsv.rb
- ex/colx.rb
- ex/findinruby
- ex/findruby
- ex/passwd_report.rb
- ex/prompt.rb
- ex/rgb.txt.gz
- ex/riocat
- ex/riogunzip
- ex/riogzip
- ex/rioprompt.rb
- ex/targz2zip
- ex/tonl
- doc/ANNOUNCE
- doc/RELEASE_NOTES
- doc/RIOIS
- doc/generators
- doc/generators/template
- doc/generators/template/html
- doc/generators/template/html/rio.css
- doc/generators/template/html/rio.rb
- doc/generators/template/html/ugly.rb
- doc/pkg_def.rb
- doc/rfc1738.txt
- doc/rfc959.txt
- test/bin
- test/bin/count_lines.rb
- test/bin/find_lines.rb
- test/bin/list_dir.rb
- test/ftp
- test/ftp/all.rb
- test/ftp/anon_copy_data.rb
- test/ftp/anon_misc.rb
- test/ftp/anon_read.rb
- test/ftp/anon_special.rb
- test/ftp/anon_write.rb
- test/ftp/ftp2ftp.rb
- test/ftp/initftpfiles.rb
- test/ftp/testdef.rb
- test/gem_runtests.rb
- test/http
- test/http/all.rb
- test/http/copy-from-http.rb
- test/http/uri-meta.rb
- test/lib
- test/lib/temp_server.rb
- test/runalltests.rb
- test/runftptests.rb
- test/runhttp.rb
- test/runhttptests.rb
- test/runtests.rb
- test/srv
- test/srv/www
- test/srv/www/htdocs
- test/srv/www/htdocs/riotest
- test/srv/www/htdocs/riotest/dir
- test/tc
- test/tc/abs.rb
- test/tc/all.rb
- test/tc/base.rb
- test/tc/base2.rb
- test/tc/cd1.rb
- test/tc/clearsel.rb
- test/tc/clone.rb
- test/tc/closeoncopy.rb
- test/tc/closeoneof.rb
- test/tc/cmdpipe.rb
- test/tc/copy-dir-samevar.rb
- test/tc/copy-from.rb
- test/tc/copy-to.rb
- test/tc/copy.rb
- test/tc/copyarray.rb
- test/tc/copydest.rb
- test/tc/copydir.rb
- test/tc/copydirlines.rb
- test/tc/copylines.rb
- test/tc/copynonex.rb
- test/tc/copysymlink.rb
- test/tc/create.rb
- test/tc/csv.rb
- test/tc/csv2.rb
- test/tc/csv_columns.rb
- test/tc/csvutil.rb
- test/tc/dir.rb
- test/tc/dir_iter.rb
- test/tc/dirautoclose.rb
- test/tc/dirent.rb
- test/tc/dirss.rb
- test/tc/each.rb
- test/tc/each_break.rb
- test/tc/edf.rb
- test/tc/empty.rb
- test/tc/emptyriodir.rb
- test/tc/entary.rb
- test/tc/entsel.rb
- test/tc/eq.rb
- test/tc/expand_path.rb
- test/tc/ext.rb
- test/tc/fileno.rb
- test/tc/files_select.rb
- test/tc/get.rb
- test/tc/getrec.rb
- test/tc/gzip.rb
- test/tc/io_each_byte.rb
- test/tc/io_read.rb
- test/tc/iometh.rb
- test/tc/likeio.rb
- test/tc/line_record_row.rb
- test/tc/lineno.rb
- test/tc/lines.rb
- test/tc/misc.rb
- test/tc/nolines.rb
- test/tc/noqae.rb
- test/tc/null.rb
- test/tc/once.rb
- test/tc/overload.rb
- test/tc/pa.rb
- test/tc/path_parts.rb
- test/tc/pathop.rb
- test/tc/paths.rb
- test/tc/pid.rb
- test/tc/piper.rb
- test/tc/programs_util.rb
- test/tc/qae.rb
- test/tc/qae_riovar.rb
- test/tc/readline.rb
- test/tc/records.rb
- test/tc/rename.rb
- test/tc/rename_assign.rb
- test/tc/riorl.rb
- test/tc/route.rb
- test/tc/selnosel.rb
- test/tc/skip.rb
- test/tc/skiplines.rb
- test/tc/split.rb
- test/tc/splitlines.rb
- test/tc/splitpath.rb
- test/tc/sub.rb
- test/tc/symlink.rb
- test/tc/symlink0.rb
- test/tc/symlink1.rb
- test/tc/synopsis.rb
- test/tc/temp.rb
- test/tc/tempdir.rb
- test/tc/tempfile.rb
- test/tc/testcase.rb
- test/tc/tonl.rb
- test/tc/truncate.rb
- test/tc/yaml.rb
- COPYING
- Rakefile
- build_doc.rb
- setup.rb
has_rdoc: true
homepage: http://rio.rubyforge.org/
post_install_message: 
rdoc_options: 
- - --show-hash
  - --line-numbers
  - -mRIO::Doc::SYNOPSIS
  - -Tdoc/generators/template/html/rio.rb
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
requirements: []

rubyforge_project: rio
rubygems_version: 1.3.1
signing_key: 
specification_version: 2
summary: Rio - Ruby I/O Facilitator
test_files: []

