#!/usr/bin/env ruby

require 'rio'

re = ARGV.shift

require 'rio/argv'
RIO::argv.each do |path|
  rio(path).norecurse('.svn','pkg').files('*.rb',proc{ |f| f.executable? and f[0] =~ /^#!.+ruby/ }) do |f|
    print f.lines[/#{re}/].map{ |line| "#{f}: #{line}" }
  end
end
__END__
ARGV.each do |path|
  rio(path).norecurse('.svn','pkg').files('*.rb',proc{ |f| f.executable? and f[0] =~ /^#!.+ruby/ }) do |f|
    print f.lines[/#{re}/].map{ |line| "#{f}: #{line}" }
  end
end

